# mkdocs.yml

site_name: "Vincent’s Digital Garden"
site_url: https://gn01167661.github.io/DigitalGarden/
docs_dir: docs           # 你的 Markdown 檔案資料夾
site_dir: site           # MkDocs build 輸出目錄

theme:
  name: material        # 使用 Material for MkDocs 主題
  custom_dir: docs/overrides        # ← 加上這行，指向你放 base.html 的 overrides/
  palette:
    primary: indigo
    accent: light-indigo

nav:
  - Home: index.md
  - Resume: resume.md
  - Knowledge Graph: graph.md 
  - embedded system:
      - 對齊原理: embedded/alignment.md
      - 記憶體區段: embedded/memory-sections.md
  - AI/ML: ai/index.md
  - 工具與流程: tools/index.md

plugins:
  - search
  - git-revision-date
  - mermaid2

extra_javascript:
  - https://d3js.org/d3.v7.min.js
  - assets/js/graph.js

extra_css:
  - assets/css/graph.css    # 如需自訂大小、背景等

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gn01167661
